<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="
             http://maven.apache.org/POM/4.0.0
             https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.jasonpercus.microbean</groupId>
    <artifactId>microbean-parent</artifactId>
    <version>1.2.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <description>Lightweight IoC framework</description>

    <modules>
        <module>microbean-archetype</module>
        <module>microbean-core</module>
        <module>microbean-openapi</module>
        <module>microbean-rest</module>
        <module>microbean-server-api</module>
        <module>microbean-server-jetty</module>
        <module>microbean-server-tomcat</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>17</java.version>
        <author>Jason Percus</author>
        <repository.url>https://github.com/jasonpercus/MicroBean</repository.url>

        <sfl4j.version>2.0.17</sfl4j.version>
        <classgraph.version>4.8.184</classgraph.version>
        <io.swagger.version>2.2.52</io.swagger.version>
        <swagger-ui.version>5.32.8</swagger-ui.version>
        <jackson.version>2.19.2</jackson.version>
        <jersey.version>4.0.2</jersey.version>
        <jakarta.servlet.version>6.1.0</jakarta.servlet.version>
        <eclipse.jetty.version>12.0.37</eclipse.jetty.version>
        <apache.tomcat.version>11.0.24</apache.tomcat.version>

        <cucumber.version>7.34.3</cucumber.version>
        <junit.plateform.version>1.14.2</junit.plateform.version>
        <junit.jupiter.version>5.14.3</junit.jupiter.version>
        <assertj.version>3.27.7</assertj.version>
        <mockito.version>5.23.0</mockito.version>
        <jna.version>5.14.0</jna.version>
    </properties>

    <dependencyManagement>
        <dependencies>


            <!-- MicroBean Framework -->
            <dependency>
                <groupId>com.jasonpercus.microbean</groupId>
                <artifactId>microbean-archetype</artifactId>
                <version>1.2.0-SNAPSHOT</version>
            </dependency>

            <dependency>
                <groupId>com.jasonpercus.microbean</groupId>
                <artifactId>microbean-core</artifactId>
                <version>1.2.0-SNAPSHOT</version>
            </dependency>

            <dependency>
                <groupId>com.jasonpercus.microbean</groupId>
                <artifactId>microbean-openapi</artifactId>
                <version>1.2.0-SNAPSHOT</version>
            </dependency>

            <dependency>
                <groupId>com.jasonpercus.microbean</groupId>
                <artifactId>microbean-rest</artifactId>
                <version>1.2.0-SNAPSHOT</version>
            </dependency>

            <dependency>
                <groupId>com.jasonpercus.microbean</groupId>
                <artifactId>microbean-server-api</artifactId>
                <version>1.2.0-SNAPSHOT</version>
            </dependency>

            <dependency>
                <groupId>com.jasonpercus.microbean</groupId>
                <artifactId>microbean-server-jetty</artifactId>
                <version>1.2.0-SNAPSHOT</version>
            </dependency>

            <dependency>
                <groupId>com.jasonpercus.microbean</groupId>
                <artifactId>microbean-server-tomcat</artifactId>
                <version>1.2.0-SNAPSHOT</version>
            </dependency>


            <!-- Autres dépendances -->
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>${sfl4j.version}</version>
            </dependency>

            <dependency>
                <groupId>io.github.classgraph</groupId>
                <artifactId>classgraph</artifactId>
                <version>${classgraph.version}</version>
            </dependency>

            <dependency>
                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-models-jakarta</artifactId>
                <version>${io.swagger.version}</version>
            </dependency>

            <dependency>
                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-jaxrs2-jakarta</artifactId>
                <version>${io.swagger.version}</version>
            </dependency>

            <dependency>
                <groupId>org.webjars</groupId>
                <artifactId>swagger-ui</artifactId>
                <version>${swagger-ui.version}</version>
            </dependency>

            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-databind</artifactId>
                <version>${jackson.version}</version>
            </dependency>

            <dependency>
                <groupId>com.fasterxml.jackson.dataformat</groupId>
                <artifactId>jackson-dataformat-yaml</artifactId>
                <version>${jackson.version}</version>
            </dependency>

            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-annotations</artifactId>
                <version>${jackson.version}</version>
            </dependency>

            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-core</artifactId>
                <version>${jackson.version}</version>
            </dependency>

            <dependency>
                <groupId>org.glassfish.jersey.core</groupId>
                <artifactId>jersey-server</artifactId>
                <version>${jersey.version}</version>
            </dependency>

            <dependency>
                <groupId>org.glassfish.jersey.containers</groupId>
                <artifactId>jersey-container-servlet</artifactId>
                <version>${jersey.version}</version>
            </dependency>

            <dependency>
                <groupId>org.glassfish.jersey.inject</groupId>
                <artifactId>jersey-hk2</artifactId>
                <version>${jersey.version}</version>
            </dependency>

            <dependency>
                <groupId>org.glassfish.jersey.media</groupId>
                <artifactId>jersey-media-json-jackson</artifactId>
                <version>${jersey.version}</version>
            </dependency>

            <dependency>
                <groupId>jakarta.servlet</groupId>
                <artifactId>jakarta.servlet-api</artifactId>
                <version>${jakarta.servlet.version}</version>
            </dependency>

            <dependency>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-server</artifactId>
                <version>${eclipse.jetty.version}</version>
            </dependency>

            <dependency>
                <groupId>org.eclipse.jetty.ee10</groupId>
                <artifactId>jetty-ee10-servlet</artifactId>
                <version>${eclipse.jetty.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.tomcat.embed</groupId>
                <artifactId>tomcat-embed-core</artifactId>
                <version>${apache.tomcat.version}</version>
            </dependency>


            <!-- Test dependencies -->
            <dependency>
                <groupId>io.cucumber</groupId>
                <artifactId>cucumber-java</artifactId>
                <version>${cucumber.version}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>io.cucumber</groupId>
                <artifactId>cucumber-junit-platform-engine</artifactId>
                <version>${cucumber.version}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.junit.platform</groupId>
                <artifactId>junit-platform-suite</artifactId>
                <version>${junit.plateform.version}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter</artifactId>
                <version>${junit.jupiter.version}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-api</artifactId>
                <version>${junit.jupiter.version}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-params</artifactId>
                <version>${junit.jupiter.version}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.assertj</groupId>
                <artifactId>assertj-core</artifactId>
                <version>${assertj.version}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-core</artifactId>
                <version>${mockito.version}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-junit-jupiter</artifactId>
                <version>${mockito.version}</version>
                <scope>test</scope>
            </dependency>

            <dependency> <!-- POUR SUPPRIMER LES WARNINGS SUR CUCUMBER -->
                <groupId>net.java.dev.jna</groupId>
                <artifactId>jna-platform</artifactId>
                <version>${jna.version}</version>
                <scope>test</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.14.1</version>
                <configuration>
                    <release>${java.version}</release>
                </configuration>
            </plugin>

            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.5.4</version>
                <configuration>
                    <argLine>-Dfile.encoding=UTF-8</argLine>
                    <properties>
                        <configurationParameters>
                            cucumber.junit-platform.naming-strategy=long
                        </configurationParameters>
                    </properties>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
                <version>2.19.1</version>
            </plugin>
        </plugins>
    </build>
</project>